/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardBody: typeof import('./src/components/ui/card-3d/CardBody.vue')['default']
    CardContainer: typeof import('./src/components/ui/card-3d/CardContainer.vue')['default']
    Cardd1: typeof import('./src/components/Cardd1.vue')['default']
    Cardd2: typeof import('./src/components/Cardd2.vue')['default']
    CardItem: typeof import('./src/components/ui/card-3d/CardItem.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    MovDiv: typeof import('./src/components/MovDiv.vue')['default']
    MovDiv2: typeof import('./src/components/MovDiv2.vue')['default']
    PassHis: typeof import('./src/components/PassHis.vue')['default']
    Word: typeof import('./src/components/Word.vue')['default']
  }
}
